apiVersion: v1
kind: Pod
metadata:
  name: citd-mplabx-cunit
spec:
  containers:
    - name: citd-mplabx-cunit
      image: artifacts.microchip.com:7999/microchip/citd/bundles/xc16-mplabx:1.50-5.35
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 8Gi